### ISSUE TITLE
Print output only on error

### ISSUE THREAD

**Issue by revolter** [piotrmurach/tty-command#41]
Is it possible to only print the command output only if it failed?

So it would print:

```
[hash] Running command
```

when it succeeds, and:

```
[hash] Running command
[hash] ** BUILD FAILED **
[hash] Finished in 2.788 seconds with exit status 65 (failed)
```

when it fails.

**Comment by piotrmurach** [comment]
Hey Lulian,

Thanks for using the gem! 

The printers are 'dumb' loggers that output anything. There is currently no such feature. However, the [print_command_exit](https://github.com/piotrmurach/tty-command/blob/master/lib/tty/command/printers/pretty.rb#L30) does allow you to hook into the status of the command. And I can imagine if you keep collecting data from other hooks, the  `print_command_out_data` and `print_command_err_data`, that is, instead of printing collect the lines and display only when the status is not zero. This could work? If you succeed please submit PR and I would be happy to add this type of printer.
